#!/usr/bin/env python3
"""
BeltWinder Matter - Web UI GZIP Compression Script
Komprimiert HTML/CSS/JS und generiert C-Header für ESP32
"""

import gzip
import sys
import os
from pathlib import Path

class Colors:
    """ANSI Color Codes für schöne Ausgabe"""
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{text:^60}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.ENDC}\n")

def print_success(text):
    print(f"{Colors.OKGREEN}✓ {text}{Colors.ENDC}")

def print_info(text):
    print(f"{Colors.OKCYAN}→ {text}{Colors.ENDC}")

def print_warning(text):
    print(f"{Colors.WARNING}⚠ {text}{Colors.ENDC}")

def print_error(text):
    print(f"{Colors.FAIL}✗ {text}{Colors.ENDC}")

def read_html_file(html_path):
    """Liest HTML-Datei ein"""
    print_info(f"Reading HTML from: {html_path}")
    
    if not os.path.exists(html_path):
        print_error(f"File not found: {html_path}")
        sys.exit(1)
    
    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            html = f.read()
        
        print_success(f"Read {len(html):,} bytes")
        return html
    except Exception as e:
        print_error(f"Failed to read file: {e}")
        sys.exit(1)

def minify_html(html, enable_minify=True):
    """
    Einfache HTML-Minification
    Entfernt überflüssige Whitespace und Kommentare
    """
    if not enable_minify:
        print_info("Minification disabled - skipping")
        return html
    
    print_info("Minifying HTML...")
    
    import re
    
    # Entferne HTML-Kommentare (außer IE conditional comments)
    html = re.sub(r'<!--(?!\[if).*?-->', '', html, flags=re.DOTALL)
    
    # Entferne überflüssige Whitespace zwischen Tags
    html = re.sub(r'>\s+<', '><', html)
    
    # Entferne Leading/Trailing Whitespace in Zeilen
    html = '\n'.join(line.strip() for line in html.split('\n'))
    
    # Entferne leere Zeilen
    html = re.sub(r'\n+', '\n', html)
    
    print_success(f"Minified to {len(html):,} bytes")
    
    return html

def compress_html(html):
    """Komprimiert HTML mit GZIP Level 9"""
    print_info("Compressing with GZIP (level 9)...")
    
    try:
        html_bytes = html.encode('utf-8')
        compressed = gzip.compress(html_bytes, compresslevel=9)
        
        original_size = len(html_bytes)
        compressed_size = len(compressed)
        ratio = (compressed_size / original_size) * 100
        savings = original_size - compressed_size
        
        print_success(f"Compressed to {compressed_size:,} bytes")
        print_info(f"Compression ratio: {ratio:.1f}%")
        print_info(f"Saved: {savings:,} bytes ({100-ratio:.1f}% reduction)")
        
        return compressed
    except Exception as e:
        print_error(f"Compression failed: {e}")
        sys.exit(1)

def generate_c_header(compressed_data, var_name="index_html_gz"):
    """Generiert C-Header mit Array und Metadata"""
    print_info("Generating C header...")
    
    lines = []
    
    # Header Guard + Includes
    lines.append("// ============================================================================")
    lines.append("// Auto-generated by compress_ui.py - DO NOT EDIT MANUALLY!")
    lines.append("// ============================================================================")
    lines.append("")
    lines.append("#ifndef INDEX_HTML_GZ_H")
    lines.append("#define INDEX_HTML_GZ_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <pgmspace.h>")
    lines.append("")
    
    # Metadata
    lines.append("// Metadata")
    lines.append(f"#define HTML_COMPRESSED_SIZE {len(compressed_data)}")
    lines.append(f"#define HTML_COMPRESSION_RATIO {(len(compressed_data) / len(compressed_data)) * 100:.1f}")
    lines.append("")
    
    # Binary Array
    lines.append(f"// Compressed HTML data ({len(compressed_data):,} bytes)")
    lines.append(f"const uint8_t {var_name}[] PROGMEM = {{")
    
    # 12 bytes per line for readability
    bytes_per_line = 12
    for i in range(0, len(compressed_data), bytes_per_line):
        chunk = compressed_data[i:i+bytes_per_line]
        hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f"    {hex_values},")
    
    lines.append("};")
    lines.append("")
    lines.append(f"const size_t {var_name}_len = sizeof({var_name});")
    lines.append("")
    lines.append("#endif // INDEX_HTML_GZ_H")
    lines.append("")
    
    return '\n'.join(lines)

def write_output(output_path, content):
    """Schreibt generierten Header in Datei"""
    print_info(f"Writing output to: {output_path}")
    
    try:
        # Stelle sicher dass Verzeichnis existiert
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        file_size = os.path.getsize(output_path)
        print_success(f"Written {file_size:,} bytes to {output_path}")
    except Exception as e:
        print_error(f"Failed to write output: {e}")
        sys.exit(1)

def main():
    """Main Entry Point"""
    
    print_header("BeltWinder UI GZIP Compression")
    
    # Argument Parsing
    if len(sys.argv) < 3:
        print_error("Usage: python compress_ui.py <input.html> <output.h> [--no-minify]")
        print_info("Example: python compress_ui.py main/web_ui.html main/index_html_gz.h")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    enable_minify = "--no-minify" not in sys.argv
    
    # Step 1: Read HTML
    html = read_html_file(input_file)
    
    # Step 2: Minify (optional)
    if enable_minify:
        html = minify_html(html)
    
    # Step 3: Compress
    compressed = compress_html(html)
    
    # Step 4: Generate C Header
    c_header = generate_c_header(compressed)
    
    # Step 5: Write Output
    write_output(output_file, c_header)
    
    # Final Summary
    print_header("Compression Complete")
    print_success("Web UI successfully compressed and ready for ESP32!")
    print_info(f"Include in your code: #include \"{os.path.basename(output_file)}\"")
    print_info(f"Array name: index_html_gz")
    print_info(f"Array size: index_html_gz_len")
    print("")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print_error("\nAborted by user")
        sys.exit(1)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
